import = [
  "~/.config/alacritty/themes/nord.toml"
]


[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular"}
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "Meslo LG S NF", style = "Italic" }
bold_italic = { family = "Meslo LG S NF", style = "Bold Italic" }
size = 13.0
offset = { y = 0}

[window]
startup_mode = "Maximized"
dimensions = { columns = 78,lines = 23 }
